### ISSUE TITLE
Incorrect output height and width on retina

### ISSUE THREAD

**Issue by dmitry-egorov** [mitchmindtree/elmesque#13]
Currently provided example has incorrect output dimensions on retina display:
![screen shot 2015-05-10 at 13 30 18](https://cloud.githubusercontent.com/assets/5902807/7553932/467c074e-f719-11e4-972f-515392c08723.png)

I was able to fix it by replacing `window.size();` with `window.draw_size();` on line 33, but I didn't test it on other platforms, so I'm not sure it's a correct solution.

Btw, maybe the example should be in a separate repository? I had to create my own project and copy contents of the example file to run it. Or maybe there's a simple way to run it, that I missed?

Anyway, thank you for a great library!

**Comment by dmitry-egorov** [comment]
Similar issue: https://github.com/PistonDevelopers/piston_window/issues/22

**Comment by mitchmindtree** [comment]
Closed by #14
