### ISSUE TITLE
Update to graphics 0.3.0

### ISSUE THREAD

**Issue by bvssvni** [mitchmindtree/elmesque#27]
This is needed to update Conrod, see https://github.com/PistonDevelopers/conrod/issues/485

**Comment by mitchmindtree** [comment]
@bvssvni I just added you as a collaborator :+1:

**Comment by bvssvni** [comment]
@mitchmindtree Thanks!

**Comment by mitchmindtree** [comment]
@bvssvni also added you as a cargo owner so you can publish too. No prob!
