### ISSUE TITLE
Provide link to living documentation?

### ISSUE THREAD

**Issue by Hoverbear** [mitchmindtree/elmesque#5]
Hi there!
I noticed you don't have any published documentation links. Are any copies available online? If not, I can help you [set up Travis to publish documentation for you](http://hoverbear.org/2015/03/07/rust-travis-github-pages/).

**Comment by mitchmindtree** [comment]
@Hoverbear hi! I don't have any documentation online yet, that would be amazing if you could help with it!

**Comment by mitchmindtree** [comment]
Woohoo [it worked](http://mitchmindtree.github.io/elmesque/elmesque/index.html)!

**Comment by Hoverbear** [comment]
Awesome!
