### ISSUE TITLE
Will not compile in Rust Beta due to box syntax

### ISSUE THREAD

**Issue by gordonbrander** [mitchmindtree/elmesque#8]
Rust Beta channel will not compile unstable features, and I guess [box syntax is an unstable feature](http://doc.rust-lang.org/book/box-syntax-and-patterns.html).

``` console
/_____/_______/.cargo/git/checkouts/elmesque-5da8cd150d113b6f/master/src/lib.rs:12:1: 12:44 error: unstable feature
/_____/_______/.cargo/git/checkouts/elmesque-5da8cd150d113b6f/master/src/lib.rs:12 #![feature(box_patterns, box_syntax, core)]
                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `elmesque`.
```

**Comment by mitchmindtree** [comment]
Ahh yes, I've been meaning to get around to stabilising elmesque (removing usage of unstable features) but haven't yet had a chance - if someone's keen to do it (should be pretty easy) i'd be more than happy to merge it! Otherwise i'll get around to it soon :+1:
